### ISSUE TITLE
Add SkaffoldYamlGenerator.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/skaffold-tools-for-java#10]
This class should generate a `skaffold.yaml` with some degree of customization, but mostly to support the case of:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
deploy:
 kubectl:
   manifests:
   - MANIFEST_PATH
```

This class should generate the YAML as a String to be able to be passed via stdin to `skaffold <command> -f -`.
